require("dotenv").config();
const nodemailer = require("nodemailer");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const transport = nodemailer.createTransport({
  host: "sandbox.smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: process.env.MAILTRAP_USER,
    pass: process.env.MAILTRAP_PASS,
  },
});

const sendOrderEmails = async (order, items) => {
  const rowsHtml = items
    .map(
      (i) => `
        <tr>
          <td>${i.name}</td>
          <td align="center">${i.quantity}</td>
          <td align="right">€${i.price}</td>
        </tr>
      `
    )
    .join("");

  try {
    await transport.sendMail({
      from: '"Shop" <orders@test.com>',
      to: "venditore@test.com",
      subject: `Nuovo ordine #${order.order_id}`,
      html: `
      <div style="background-color:#f2f4f8;padding:40px 0;font-family:Arial,Helvetica,sans-serif;">
        <table align="center" width="100%" cellpadding="0" cellspacing="0"
            style="max-width:620px;background:#ffffff;border-radius: 5px;overflow:hidden;box-shadow:0 8px 30px rgba(0,0,0,0.08);">

            <tr>
                <td style="background:linear-gradient(135deg,#111111,#333333);padding:30px 40px;text-align:center;">
                    <div style="text-align:center; margin:10px 0;">
                        <img src="http://localhost:3000/logo_dualia_welcome.jpeg" alt="DUALIA logo"
                            style="max-width:100px;" />
                    </div>
                    <h1 style="margin:0;font-size:24px;color:#ffffff;letter-spacing:0.5px;">
                        New Order Received
                    </h1>
                    <p style="margin:8px 0 0;font-size:14px;color:#cccccc;">
                        Your shop has just made a sale
                    </p>
                </td>
            </tr>

            <tr>
                <td style="padding:40px;">
                    <p style="font-size:16px;color:#333333;margin-top:0;line-height:1.6;">
                        Hello,<br>
                        you have just done a <strong>new purchase</strong> in your online store DUALIA.
                    </p>

                    <table width="100%" cellpadding="12" cellspacing="0"
                        style="border-collapse:collapse;margin:25px 0;border-radius:8px;overflow:hidden;">
                        <tr>
                            <td colspan="2" style="background:#f5f7fa;font-weight:bold;color:#111111;font-size:15px;">
                                Order Details
                            </td>
                        </tr>
                        <tr>
                            <td style="background:#ffffff;color:#555555;width:40%;">Order Number</td>
                            <td style="background:#ffffff;font-weight:bold;">#${order.order_id}</td>
                        </tr>
                        <tr>
                            <td style="background:#f9fafc;color:#555555;">Customer</td>
                            <td style="background:#f9fafc;">${order.first_name} ${order.last_name}</td>
                        </tr>
                        <tr>
                            <td style="background:#ffffff;color:#555555;">Email</td>
                            <td style="background:#ffffff;">${order.email}</td>
                        </tr>
                        <tr>
                            <td style="background:#f9fafc;color:#555555;">Order Total</td>
                            <td style="background:#f9fafc;font-size:18px;font-weight:bold;color:#111111;">
                                € ${order.total_amount}
                            </td>
                        </tr>
                    </table>

                    <div style="text-align:center;margin:35px 0;">
                        <a href="http://localhost:5173/" style="background:#111111;color:#e3be85;text-decoration:none;
                        padding:14px 28px;border-radius:1px;
                        font-size:14px;font-weight:bold;display:inline-block;">
                            Go to Admin Panel
                        </a>
                    </div>

                    <p style="font-size:14px;color:#666666;line-height:1.6;margin-bottom:0;">
                        Access the admin panel to review the details, manage shipping, and update the order status.
                    </p>
                </td>
            </tr>

            <tr>
                <td style="background:#f5f7fa;padding:20px 30px;text-align:center;">
                    <p style="margin:0;font-size:12px;color:#888888;line-height:1.5;">
                        This email was automatically generated by your shop.<br>
                        © <strong>DUALIA</strong> – All rights reserved
                    </p>
                </td>
            </tr>

        </table>
    </div>
      `,
    });
  } catch (err) {
    console.error("Errore invio email venditore:", err);
  }

  await sleep(10_000);

  try {
    await transport.sendMail({
      from: '"Shop" <orders@test.com>',
      to: order.email,
      subject: `Conferma ordine #${order.order_id}`,
      html: `
        <h2>Conferma ordine #${order.order_id}</h2>

        <p>
          Ciao ${order.first_name} ${order.last_name},<br/>
          abbiamo ricevuto il tuo ordine del ${order.date}.
        </p>

        <table width="100%" cellpadding="6" cellspacing="0" border="1">
          <thead>
            <tr>
              <th align="left">Prodotto</th>
              <th>Qtà</th>
              <th align="right">Prezzo</th>
            </tr>
          </thead>
          <tbody>
            ${rowsHtml}
          </tbody>
        </table>

        <p><strong>Totale:</strong> €${order.total_amount}</p>

        ${order.free_shipping
          ? "<p><strong>Spedizione gratuita</strong></p>"
          : ""
        }

        <h4>Indirizzo di spedizione</h4>
        <p>
          ${order.street}, ${order.house_number}<br/>
          ${order.postal_code} ${order.city} (${order.state})<br/>
          ${order.country}
        </p>
      `,
    });
  } catch (err) {
    console.error("Errore invio email cliente:", err);
  }
};

module.exports = { sendOrderEmails };
